"use strict";
let valor73_173 = "Olá, TypeScript!";
let comprimento73 = valor73_173.length;
console.log(comprimento73);
let valor73_1 = "Olá, TypeScript!";
let comprimento73_1 = valor73_1.length;
console.log(comprimento73_1);
const carro73 = 'Corolla';
const tamanhoString73 = carro73.length;
console.log(`O tamanho da string é ${tamanhoString73}`);
console.log(tamanhoString73);
